services:
  - type: web
    name: baby-sleep-classifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0 